apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::336893118690:role/eksctl-simple-jwt-api-nodegroup-ng-NodeInstanceRole-D3G1ZpcniwfC
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
     rolearn: arn:aws:iam::336893118690:role/UdacityFlaskDeployCBKubectlRole
     username: build  
kind: ConfigMap
metadata:
  creationTimestamp: "2023-10-25T04:14:25Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1555"
  uid: ed491fda-9240-4aa3-bf88-805f4c0e0023
